trigger:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'app'
    publishLocation: 'Container'
- main   # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Use Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # Adjust based on your Angular version
  displayName: 'Install Node.js'

# Step 2: Install dependencies
- script: |
    npm ci
  displayName: 'Install dependencies'

# Step 3: Build Angular app
- script: |
    npm run build -- --configuration=production
  displayName: 'Build Angular app'

# Step 4: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
